config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'categories/:id(/page/:page)', as: :category, to: 'categories#show'
  get 'contact/', as: :api_contact, to: 'api#contact'
  # resources :categories
  resources :news, as: :post

  devise_for :users, as: :frontend


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  authenticate :frontend_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  mount Commontator::Engine => '/commontator'
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
end

app/views/widgets/partials/_render_image_or_video.html.haml
- if post.has_video_info?
  .video-section.featured-wrap
    .frame.themeum-overlay-wrap.yes{style: "background: url(#{post.get_video_info.thumbnail_large}) center no-repeat; background-size: cover"}
    = link_to 'Смотреть видео', '#', class: %i(link-video)
    != post.get_video_info.embed_code(iframe_attributes: { width: '100%', height: '100%', 'data-key': 'value' })
    %span.overlay
- elsif post.video_content.present?
  .video-section.featured-wrap.without_layout.category_index
    = link_to 'Смотреть видео', '#', class: %i(link-video)
    != post.video_content.html_safe
    %span.overlay
- else
  = link_to post_path(post), class: %i(featured_img), title: post.title  do
    = image_tag post.main_image(:medium), alt: post.title
    %span.overlay