config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'categories/:id(/page/:page)', as: :category, to: 'categories#show'
  get 'contact/', as: :api_contact, to: 'api#contact'
  # resources :categories
  resources :news, as: :post

  devise_for :users, as: :frontend


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  authenticate :frontend_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  mount Commontator::Engine => '/commontator'
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin
end

app/views/layouts/partials/_footer.html.haml
%footer#footer
  .footer_top
    .row
      .col-lg-4.col-md-4.col-sm-4
        .footer_widget.wow.fadeInLeftBig
          %h2 Мы рады стараться для вас!
          %object#mySwf{:classid => "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000", :height => "300", :width => "234"}
            %param{:name => "src", :value => "https://cp.beget.com/banners/new/234x300.swf"}/
            %param{:name => "flashVars", :value => "id_number=88338"}/
            %embed{:flashvars => "id_number=88338", :height => "300", :name => "mySwf", :src => "https://cp.beget.com/banners/new/234x300.swf", :width => "234"}
      .col-lg-4.col-md-4.col-sm-4
        .footer_widget.wow.fadeInDown
          %h2 Разделы
          %ul.tag_nav
            - @footer_categories.each do |category|
              %li
                = link_to category.title, category_path(category)

      .col-lg-4.col-md-4.col-sm-4
        .footer_widget.wow.fadeInRightBig
          %h2 Инфо:
          %p
            Просим обратить Ваше внимание, что весь контент (или почти весь:), размещенный на сайте, не является авторским!
            Администрация сайта не несет ответсвенность за содержание постов.
          .banner
            %object#mySwf2{:classid => "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000", :height => "60", :width => "234"}
              %param{:name => "src", :value => "https://cp.beget.com/promo_data/new/234x60.swf"}/
              %param{:name => "flashVars", :value => "id_number=88338"}/
              %embed{:flashvars => "id_number=88338", :height => "60", :name => "mySwf", :src => "https://cp.beget.com/promo_data/new/234x60.swf", :width => "234"}
  .footer_bottom
    %p.copyright
      Copyright ©
      = Date.today.strftime('%Y')
      = link_to 'AllNews', root_path
    %p.developer Developed By AtrDevelop

app/views/layouts/partials/_header.html.haml
%header#header
  .row
    .col-lg-12.col-md-12.col-sm-12
      .header_top
        .header_top_left
          %ul.top_nav
            %li
              = link_to 'Главная', root_path
            %li
              = link_to 'Контакты', '#'
        .header_top_right
          %p
            = I18n.l(Time.now, format: '%A, %d %B %Y')
    .col-lg-12.col-md-12.col-sm-12
      .header_bottom
        .logo_area
          = link_to root_path, class: :logo do
            .logo{style: 'margin-left: 14px'}
              %span{style: 'color: #000'}
                %strong All
              %span
                %strong News
        .add_banner
          %object#mySwf{:classid => "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000", :height => "90", :width => "728"}
            %param{:name => "src", :value => "https://cp.beget.com/banners/new/728x90.swf"}/
            %param{:name => "flashVars", :value => "id_number=88338"}/
            %embed{:flashvars => "id_number=88338", :height => "90", :name => "mySwf", :src => "https://cp.beget.com/banners/new/728x90.swf", :width => "728"}

app/views/layouts/partials/_main_nav_menu.html.haml
%section#navArea
  %nav.navbar.navbar-inverse{role: 'navigation'}
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-control': 'navbar', 'aria-expande': 'false', 'data-targe': '#navbar', 'data-toggl': 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.main_nav
        %li.active
          = link_to root_path do
            %span.fa.fa-home.desktop-home
            %span.mobile-show Главная
        - if defined?(categories) && categories.present?
          - categories.each do |category|
            = render 'layouts/partials/menu_item', locals: {category: category}

app/views/layouts/partials/_menu_item.html.haml
- unless locals[:category].children.present?
  %li
    = link_to locals[:category].title, category_path(locals[:category])
- else locals[:category].children.present?
  %li.dropdown
    = link_to locals[:category].title, '#', {class: 'dropdown-toggle', 'aria-expande': 'false', 'data-toggl': 'dropdown', role: 'button'}
    %ul.dropdown-menu{role: :menu}
      - locals[:category].children.each do |category|
        = render 'layouts/partials/menu_item', locals: {category: category}

app/views/layouts/partials/_right_navbar.html.haml
.single_sidebar.wow.fadeInDown
  %h2
    %span Страницы
  %ul
    %li
      %a{href: '#'} Связь с нами!
    %li
      %a{href: '#'} Вход